const s = require('generate-string')

module.exports = function generateCode (hyperswitch) {
  let str = ''
  str += '// This file is autogenerated by the hyperswitch compiler\n'
  str += '/* eslint-disable camelcase */\n'
  str += '\n'
  str += 'const { c, b4a, assert } = require(\'hyperswitch/runtime\')\n'
  str += 'const { version, resolveStruct } = require(\'./messages.js\')\n'
  str += '\n'

  str += 'class Router {\n'
  str += '  constructor () {\n'
  str += '    this._missingHandlers = new Map([\n'
  for (let i = 0; i < hyperswitch.handlers.length; i++) {
    const handler = hyperswitch.handlers[i]
    str += `      [${s(handler.name)}, ${handler.id}]`
    if (i !== hyperswitch.handlers.length - 1) str += ','
    str += '\n'
  }
  str += '    ])\n'
  str += '\n'
  for (const handler of hyperswitch.handlers) {
    str += `    this._handler${handler.id} = null\n`
  }
  str += '  }\n'
  str += '\n'
  str += '  add (name, handler) {\n'
  str += '    switch (name) {\n'
  for (const handler of hyperswitch.handlers) {
    str += `      case ${s(handler.name)}:\n`
    str += `        this._handler${handler.id} = handler\n`
    str += '        break\n'
  }
  str += '      default:\n'
  str += '        throw new Error(\'Cannot register a handler for a nonexistent route: \' + name)\n'
  str += '    }\n'
  str += '    this._missingHandlers.delete(name)\n'
  str += '  }\n'
  str += '\n'
  str += '  dispatch (encoded) {\n'
  str += '    if (this._missingHandlers.size > 0) {\n'
  str += '      assert(\'Missing handlers for: \' + [...this._missingHandlers.keys()])\n'
  str += '    }\n'
  str += '\n'
  str += '    const state = { buffer: encoded, start: 0, end: encoded.byteLength }\n'
  str += '    const id = c.uint.decode(state)\n'
  str += '\n'
  str += '    switch (id) {\n'
  for (const handler of hyperswitch.handlers) {
    str += `      case ${handler.id}:\n`
    str += `        return this._handler${handler.id}(resolveStruct(${s(handler.requestType)}).decode(state))\n`
  }
  str += '      default:\n'
  str += '        throw new Error(\'Handler not found for ID:\' + message.id)\n'
  str += '    }\n'
  str += '  }\n'
  str += '}\n'

  str += '\n'

  str += 'function dispatch (name, message, opts) {\n'
  str += '  const state = c.state()\n'
  str += '  let enc = null\n'
  str += '  switch (name) {\n'
  for (const handler of hyperswitch.handlers) {
    str += `    case ${s(handler.name)}:\n`
    str += `      enc = resolveStruct(${s(handler.requestType)}, opts && opts.version)\n`
    str += `      c.uint.preencode(state, ${handler.id})\n`
    str += '      enc.preencode(state, message)\n'
    str += '      state.buffer = b4a.allocUnsafe(state.end)\n'
    str += `      c.uint.encode(state, ${handler.id})\n`
    str += '      enc.encode(state, message)\n'
    str += '      return state.buffer\n'
  }
  str += '    default:\n'
  str += '      throw new Error(\'Handler not found for name: \' + name)\n'
  str += '  }\n'
  str += '}\n'
  str += '\n'

  str += 'module.exports = {\n'
  str += '  version,\n'
  str += '  dispatch,\n'
  str += '  Router\n'
  str += '}\n'

  return str
}
